### ISSUE TITLE
Suggestion: Make wrapped objects public

### ISSUE THREAD

**Issue by victorgawk** [marschall/jakarta-jms-adapter#3]
Hi. thank you for making this adapter. It's being useful to me.

I would like to ask if it's possible to make `JakartaQueue` class and its constructor public?

I am using a Weblogic JMS server and use a context lookup to get a `javax.jms.Queue` instance through JNDI but I can't use JakartaQueue class to wrap into `jakarta.jms.Queue` because it's package protected.

**Comment by marschall** [comment]
I released 1.3.0 to Maven Central. Let me know if this works for you.

**Comment by marschall** [comment]
I don't know enough about WebLogic, I don't assume there is a way to hook into JNDI and register your own objects, eg through ` ObjectFactory`?

**Comment by victorgawk** [comment]
The queue instance from Weblogic JMS server is obtained through a JNDI lookup. For instance:
```java
import java.util.Hashtable;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import com.github.marschall.jakartajmsadapter.JakartaQueue;
import jakarta.jms.Queue;

public class JndiLookupExample {

  public static void main(String[] args) throws NamingException {
    // creates a hashtable with the Weblogic server parameters
    Hashtable<String, String> env = new Hashtable<>();
    env.put("java.naming.factory.initial", "weblogic.jndi.WLInitialContextFactory");
    env.put("java.naming.provider.url", "t3://host:port");

    // creates the initial context for the JNDI lookup
    InitialContext ctx = new InitialContext(env);

    // obtain a JMS Queue by JNDI lookup
    Queue queue = new JakartaQueue((javax.jms.Queue) ctx.lookup("queue JNDI here"));
  }

}
```

**Comment by marschall** [comment]
With 1.6.0 the `JakartaQueue` is no longer public. The way to get a queue instance is 

```java
InitialContext ctx = new InitialContext(env);

Queue queue = Wrapper.fromJavaxQueue((javax.jms.Queue) ctx.lookup("queue JNDI here"));
```
